In [134]:
import pandas as pd
import numpy as np

In [135]:
from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/Carisurg_AI_Training_Program/Week_0/EmergencyTriageDataset_Reduced_Dirty.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [136]:
df_raw = pd.read_csv(path)

In [137]:
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [138]:
unique_genders = list(df_raw.Gender.unique())
print(f"Unique genders: {unique_genders}")

Unique genders: ['0', 'Male', 'Female', 'FEMALE', '1', 'MALE']

In [139]:
print(f"Number of Null Values originally: {df_raw['Gender'].isnull().sum()}")

Number of Null Values originally: 0

#**Cleaning Gender using just Mapping**

Genders can be mapped unto various integers. This has the advatage of being easier and faster to do opertations on compared to objects.

Here we will map male as 1, female as 0 and other as 2.
Those are the only categories presnt in the data currently.

In [140]:
gender_map = {
    '0': 0,
    'Male': 1,
    'Female': 0,
    'FEMALE': 0,
    '1': 1,
    'MALE': 1
}

df_clean =  df_raw.copy()
df_clean['Gender'] = df_raw['Gender'].map(gender_map)
df_clean = df_clean.fillna(2)

df_clean.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20       1  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77       0  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86       0  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42       1  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75       0  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25       1  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82       0  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [141]:
print(f"Number of Null Values Left: {df_clean['Gender'].isnull().sum()}")

Number of Null Values Left: 0

#**Cleaning Gender using Dummy Variables**

The previous data cleaning implementation had the problem that it required us to map genders unto arbitray integers. This makes debugging more difficult and makes the mapping inherently subjective.

In order to avoid this, Dummy Variables can be used instead in order to encode categorical data into unique booleans for each class.

In [142]:
#we first need to map the values in order to standardize the format the genders comein.
gender_encoder_map = {
    '0': 'Female',
    'Male': 'Male',
    'Female': 'Female',
    'FEMALE': 'Female',
    '1': 'Male',
    'MALE': 'Male'
}

df_encoded =  df_raw.copy()
df_encoded['Gender'] = df_raw['Gender'].map(gender_encoder_map)
df_encoded = df_encoded.fillna('Other')

df_encoded.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34  Female  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23  Female   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  Female  15.0  150   90.0   110.0   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67  Female  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [143]:
encoded_unique_genders = list(df_encoded.Gender.unique())
print(f"Encoded Unique genders: {encoded_unique_genders}")

Encoded Unique genders: ['Female', 'Male']

In [144]:
df_clean_encoded = pd.get_dummies(df_encoded, columns=['Gender']) #creates column for each category. however, they come as booleans.
df_clean_encoded.head(10)

,ID,Age,GCS,SBP,DBP,MAP,pulse,Temp,RR,Fio2,Gender_Female,Gender_Male
0,1,34,15.0,93,67.0,75.67,128.0,36.8,14.0,21.0,True,False
1,2,20,15.0,130,90.0,103.33,80.0,37.0,16.0,21.0,False,True
2,3,77,14.0,163,105.0,124.33,92.0,36.8,18.0,21.0,True,False
3,4,23,8.0,100,60.0,73.33,100.0,37.0,12.0,100.0,True,False
4,5,86,15.0,150,90.0,110.0,85.0,37.0,19.0,21.0,True,False
5,6,42,15.0,100,60.0,73.33,99.0,37.0,20.0,21.0,False,True
6,7,75,15.0,120,80.0,93.33,99.0,37.0,25.0,21.0,True,False
7,8,25,15.0,100,50.0,66.67,85.0,37.0,25.0,21.0,False,True
8,9,67,15.0,110,70.0,83.33,78.0,37.0,16.0,21.0,True,False
9,11,82,15.0,153,82.0,105.67,130.0,37.0,19.0,21.0,True,False

In [145]:
df_clean_encoded['Gender_Female'] = df_clean_encoded['Gender_Female'].astype(int) #casts the boolean to integer seeing as that was the data type used in tutorial
df_clean_encoded['Gender_Male'] = df_clean_encoded['Gender_Male'].astype(int) #casts the boolean to integer seeing as that was the data type used in tutorial
#df_clean_encoded['Gender_Other'] = df_clean_encoded['Gender_Other'].astype(int) #casts the boolean to integer seeing as that was the data type used in tutorial

df_clean_encoded.head(10)

,ID,Age,GCS,SBP,DBP,MAP,pulse,Temp,RR,Fio2,Gender_Female,Gender_Male
0,1,34,15.0,93,67.0,75.67,128.0,36.8,14.0,21.0,1,0
1,2,20,15.0,130,90.0,103.33,80.0,37.0,16.0,21.0,0,1
2,3,77,14.0,163,105.0,124.33,92.0,36.8,18.0,21.0,1,0
3,4,23,8.0,100,60.0,73.33,100.0,37.0,12.0,100.0,1,0
4,5,86,15.0,150,90.0,110.0,85.0,37.0,19.0,21.0,1,0
5,6,42,15.0,100,60.0,73.33,99.0,37.0,20.0,21.0,0,1
6,7,75,15.0,120,80.0,93.33,99.0,37.0,25.0,21.0,1,0
7,8,25,15.0,100,50.0,66.67,85.0,37.0,25.0,21.0,0,1
8,9,67,15.0,110,70.0,83.33,78.0,37.0,16.0,21.0,1,0
9,11,82,15.0,153,82.0,105.67,130.0,37.0,19.0,21.0,1,0

In [146]:
print(df_clean_encoded.dtypes)

ID                int64
Age               int64
GCS              object
SBP              object
DBP              object
MAP              object
pulse            object
Temp             object
RR               object
Fio2             object
Gender_Female     int64
Gender_Male       int64
dtype: object